/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ArcadiaProjectsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/types.ts
var VIEW_TYPE_ARCADIA_PROJECTS = "arcadia-projects-view";
var DEFAULT_SETTINGS = {
  projectFolder: "",
  statusProperty: "status",
  statusValues: ["todo", "in-progress", "done"],
  dateProperty: "due",
  defaultView: "table",
  cardFields: ["status", "due", "tags"],
  licenseKey: "",
  licenseStatus: null,
  isPro: false
};

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/license.ts
var import_obsidian = require("obsidian");
var LICENSE_CACHE_DURATION = 24 * 60 * 60 * 1e3;
async function validateLicense(licenseKey, instanceName = "obsidian") {
  var _a, _b, _c;
  try {
    const response = await (0, import_obsidian.requestUrl)({
      url: "https://api.lemonsqueezy.com/v1/licenses/validate",
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Accept": "application/json"
      },
      body: JSON.stringify({ license_key: licenseKey, instance_name: instanceName })
    });
    const data = response.json;
    if (data.valid) {
      return {
        valid: true,
        instanceId: (_a = data.instance) == null ? void 0 : _a.id,
        customerEmail: (_b = data.meta) == null ? void 0 : _b.customer_email,
        expiresAt: (_c = data.license_key) == null ? void 0 : _c.expires_at,
        lastChecked: Date.now()
      };
    }
    return { valid: false, lastChecked: Date.now() };
  } catch (e) {
    return { valid: false, lastChecked: Date.now() };
  }
}

// src/settings.ts
var ArcadiaProjectsSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("General").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Project folder").setDesc("Path to the folder containing your project notes (e.g. Projects/)").addText(
      (text) => text.setPlaceholder("Projects/").setValue(this.plugin.settings.projectFolder).onChange((value) => {
        this.plugin.settings.projectFolder = value.trim();
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Status property").setDesc("Frontmatter property used for status (used as kanban columns)").addText(
      (text) => text.setPlaceholder("status").setValue(this.plugin.settings.statusProperty).onChange((value) => {
        this.plugin.settings.statusProperty = value.trim();
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Status values").setDesc("Comma-separated list of status values (defines kanban column order)").addText(
      (text) => text.setPlaceholder("todo, in-progress, done").setValue(this.plugin.settings.statusValues.join(", ")).onChange((value) => {
        this.plugin.settings.statusValues = value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Date property").setDesc("Frontmatter property used for due dates").addText(
      (text) => text.setPlaceholder("due").setValue(this.plugin.settings.dateProperty).onChange((value) => {
        this.plugin.settings.dateProperty = value.trim();
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Default view").setDesc("Which view to show when opening the project panel").addDropdown(
      (dropdown) => dropdown.addOption("table", "Table").addOption("kanban", "Kanban").setValue(this.plugin.settings.defaultView).onChange((value) => {
        this.plugin.settings.defaultView = value;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Card display fields").setDesc("Comma-separated list of frontmatter properties to show on kanban cards").addText(
      (text) => text.setPlaceholder("status, due, tags").setValue(this.plugin.settings.cardFields.join(", ")).onChange((value) => {
        this.plugin.settings.cardFields = value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("License").setHeading();
    const licenseStatus = this.plugin.settings.licenseStatus;
    const isPro = this.plugin.settings.isPro && (licenseStatus == null ? void 0 : licenseStatus.valid);
    const statusDesc = isPro ? `Active${(licenseStatus == null ? void 0 : licenseStatus.customerEmail) ? ` (${licenseStatus.customerEmail})` : ""}${(licenseStatus == null ? void 0 : licenseStatus.expiresAt) ? ` - expires ${licenseStatus.expiresAt}` : ""}` : "No active license. Enter your license key and click Validate.";
    const licenseStatusEl = containerEl.createEl("p", {
      text: `License status: ${statusDesc}`,
      cls: isPro ? "mod-success" : "mod-warning"
    });
    new import_obsidian2.Setting(containerEl).setName("License key").setDesc("Enter your license key from Lemon Squeezy.").addText(
      (text) => text.setPlaceholder("XXXX-XXXX-XXXX-XXXX").setValue(this.plugin.settings.licenseKey).onChange((value) => {
        this.plugin.settings.licenseKey = value.trim();
        void this.plugin.saveSettings();
      })
    ).addButton(
      (btn) => btn.setButtonText("Validate").setCta().onClick(() => {
        const key = this.plugin.settings.licenseKey.trim();
        if (!key)
          return;
        btn.setButtonText("Checking...").setDisabled(true);
        void validateLicense(key).then((status) => {
          this.plugin.settings.licenseStatus = status;
          this.plugin.settings.isPro = status.valid;
          void this.plugin.saveSettings().then(() => {
            btn.setButtonText("Validate").setDisabled(false);
            if (status.valid) {
              licenseStatusEl.textContent = `License status: Active${status.customerEmail ? ` (${status.customerEmail})` : ""}`;
              licenseStatusEl.className = "mod-success";
            } else {
              licenseStatusEl.textContent = "License status: Invalid or expired. Check your key and try again.";
              licenseStatusEl.className = "mod-warning";
            }
          });
        });
      })
    );
    new import_obsidian2.Setting(containerEl).addButton(
      (btn) => btn.setButtonText("Get premium").onClick(() => {
        window.open("https://arcadia-studio.lemonsqueezy.com", "_blank");
      })
    );
  }
};

// src/data.ts
var import_obsidian3 = require("obsidian");
var ProjectDataManager = class extends import_obsidian3.Events {
  constructor(app, settings) {
    super();
    this.notes = [];
    this.metadataCacheRef = null;
    this.vaultRef = null;
    this.vaultDeleteRef = null;
    this.app = app;
    this.settings = settings;
  }
  /** Start listening for vault changes */
  startListening() {
    this.metadataCacheRef = this.app.metadataCache.on("changed", (file) => {
      if (this.isProjectFile(file)) {
        this.refresh();
      }
    });
    this.vaultRef = this.app.vault.on("create", (file) => {
      if (file instanceof import_obsidian3.TFile && this.isProjectFile(file)) {
        this.refresh();
      }
    });
    this.vaultDeleteRef = this.app.vault.on("delete", (file) => {
      if (file instanceof import_obsidian3.TFile && this.isProjectFile(file)) {
        this.refresh();
      }
    });
  }
  /** Stop listening for vault changes */
  stopListening() {
    if (this.metadataCacheRef) {
      this.app.metadataCache.offref(this.metadataCacheRef);
      this.metadataCacheRef = null;
    }
    if (this.vaultRef) {
      this.app.vault.offref(this.vaultRef);
      this.vaultRef = null;
    }
    if (this.vaultDeleteRef) {
      this.app.vault.offref(this.vaultDeleteRef);
      this.vaultDeleteRef = null;
    }
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  /** Check if a file belongs to the configured project folder */
  isProjectFile(file) {
    if (!this.settings.projectFolder)
      return false;
    const folderPath = this.normalizePath(this.settings.projectFolder);
    return file.path.startsWith(folderPath) && file.extension === "md";
  }
  normalizePath(path) {
    let p = path.replace(/\\/g, "/");
    if (!p.endsWith("/"))
      p += "/";
    return p;
  }
  /** Refresh the notes array from vault */
  refresh() {
    this.notes = this.loadNotes();
    this.trigger("data-changed");
  }
  /** Load all project notes from the configured folder */
  loadNotes() {
    const folderPath = this.settings.projectFolder;
    if (!folderPath)
      return [];
    const normalizedPath = this.normalizePath(folderPath);
    const folder = this.app.vault.getAbstractFileByPath(
      normalizedPath.endsWith("/") ? normalizedPath.slice(0, -1) : normalizedPath
    );
    if (!folder || !(folder instanceof import_obsidian3.TFolder))
      return [];
    const notes = [];
    this.collectMarkdownFiles(folder, notes);
    return notes;
  }
  /** Recursively collect .md files from a folder */
  collectMarkdownFiles(folder, notes) {
    for (const child of folder.children) {
      if (child instanceof import_obsidian3.TFile && child.extension === "md") {
        const note = this.buildProjectNote(child);
        notes.push(note);
      } else if (child instanceof import_obsidian3.TFolder) {
        this.collectMarkdownFiles(child, notes);
      }
    }
  }
  /** Build a ProjectNote from a TFile using MetadataCache */
  buildProjectNote(file) {
    var _a;
    const cache = this.app.metadataCache.getFileCache(file);
    const frontmatter = (_a = cache == null ? void 0 : cache.frontmatter) != null ? _a : {};
    const properties = {};
    for (const key of Object.keys(frontmatter)) {
      if (key === "position")
        continue;
      properties[key] = frontmatter[key];
    }
    return {
      file,
      title: file.basename,
      properties
    };
  }
  /** Get all notes */
  getNotes() {
    return this.notes;
  }
  /** Get notes filtered by a text query across all property values */
  getFilteredNotes(query) {
    if (!query.trim())
      return this.notes;
    const lower = query.toLowerCase();
    return this.notes.filter((note) => {
      if (note.title.toLowerCase().includes(lower))
        return true;
      for (const val of Object.values(note.properties)) {
        if (String(val).toLowerCase().includes(lower))
          return true;
      }
      return false;
    });
  }
  /** Get notes sorted by a column */
  getSortedNotes(notes, sort) {
    if (!sort)
      return notes;
    const sorted = [...notes];
    sorted.sort((a, b) => {
      let aVal = sort.column === "title" ? a.title : a.properties[sort.column];
      let bVal = sort.column === "title" ? b.title : b.properties[sort.column];
      if (aVal == null)
        aVal = "";
      if (bVal == null)
        bVal = "";
      const aStr = String(aVal).toLowerCase();
      const bStr = String(bVal).toLowerCase();
      const cmp = aStr.localeCompare(bStr);
      return sort.direction === "asc" ? cmp : -cmp;
    });
    return sorted;
  }
  /** Get notes grouped by a property value (for Kanban) */
  getGroupedNotes(property, orderedValues) {
    const groups = /* @__PURE__ */ new Map();
    for (const val of orderedValues) {
      groups.set(val, []);
    }
    groups.set("__uncategorized__", []);
    for (const note of this.notes) {
      const rawVal = note.properties[property];
      const val = rawVal != null ? (typeof rawVal === "object" ? JSON.stringify(rawVal) : String(rawVal)).trim() : "";
      if (val && groups.has(val)) {
        groups.get(val).push(note);
      } else if (val) {
        if (!groups.has(val)) {
          groups.set(val, []);
        }
        groups.get(val).push(note);
      } else {
        groups.get("__uncategorized__").push(note);
      }
    }
    return groups;
  }
  /** Collect all unique frontmatter property keys across all notes */
  getAllPropertyKeys() {
    const keys = /* @__PURE__ */ new Set();
    for (const note of this.notes) {
      for (const key of Object.keys(note.properties)) {
        keys.add(key);
      }
    }
    return Array.from(keys).sort();
  }
  /** Update a note's frontmatter property */
  async updateNoteProperty(file, property, value) {
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      fm[property] = value;
    });
  }
  /** Create a new note in the project folder with given properties */
  async createNote(title, properties) {
    const folderPath = this.settings.projectFolder.replace(/\/$/, "");
    const filePath = `${folderPath}/${title}.md`;
    let yaml = "---\n";
    for (const [key, val] of Object.entries(properties)) {
      yaml += `${key}: ${val}
`;
    }
    yaml += "---\n";
    const file = await this.app.vault.create(filePath, yaml);
    return file;
  }
};

// src/project-view.ts
var import_obsidian5 = require("obsidian");

// src/table-view.ts
var TableView = class {
  constructor(app, containerEl, dataManager, settings) {
    this.sortState = null;
    this.filterQuery = "";
    this.filterInputEl = null;
    this.app = app;
    this.containerEl = containerEl;
    this.dataManager = dataManager;
    this.settings = settings;
  }
  render() {
    this.containerEl.empty();
    this.containerEl.addClass("arcadia-projects-table-container");
    const filterBar = this.containerEl.createDiv({ cls: "arcadia-projects-filter-bar" });
    this.filterInputEl = filterBar.createEl("input", {
      cls: "arcadia-projects-filter-input",
      attr: { type: "text", placeholder: "Filter notes..." }
    });
    this.filterInputEl.value = this.filterQuery;
    this.filterInputEl.addEventListener("input", () => {
      this.filterQuery = this.filterInputEl.value;
      this.renderTable();
    });
    this.containerEl.createDiv({ cls: "arcadia-projects-table-wrapper" });
    this.renderTable();
  }
  renderTable() {
    const wrapper = this.containerEl.querySelector(".arcadia-projects-table-wrapper");
    if (!wrapper)
      return;
    wrapper.innerHTML = "";
    let notes = this.dataManager.getFilteredNotes(this.filterQuery);
    notes = this.dataManager.getSortedNotes(notes, this.sortState);
    if (notes.length === 0) {
      const empty = wrapper.createDiv({ cls: "arcadia-projects-empty" });
      empty.setText(
        this.dataManager.getNotes().length === 0 ? "No notes found. Check your project folder setting." : "No notes match the current filter."
      );
      return;
    }
    const allKeys = this.dataManager.getAllPropertyKeys();
    const columns = ["title", ...allKeys];
    const table = wrapper.createEl("table", { cls: "arcadia-projects-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    for (const col of columns) {
      const th = headerRow.createEl("th", { cls: "arcadia-projects-th" });
      const headerContent = th.createDiv({ cls: "arcadia-projects-th-content" });
      headerContent.createSpan({ text: this.formatColumnName(col) });
      if (this.sortState && this.sortState.column === col) {
        const sortIcon = headerContent.createSpan({ cls: "arcadia-projects-sort-icon" });
        sortIcon.setText(this.sortState.direction === "asc" ? " \u25B2" : " \u25BC");
      }
      th.addEventListener("click", () => {
        this.toggleSort(col);
      });
    }
    const tbody = table.createEl("tbody");
    for (const note of notes) {
      const row = tbody.createEl("tr", { cls: "arcadia-projects-row" });
      for (const col of columns) {
        const td = row.createEl("td", { cls: "arcadia-projects-td" });
        if (col === "title") {
          const link = td.createEl("a", {
            cls: "arcadia-projects-note-link",
            text: note.title
          });
          link.addEventListener("click", (e) => {
            e.preventDefault();
            void this.app.workspace.openLinkText(note.file.path, "", false);
          });
        } else {
          const val = note.properties[col];
          td.setText(this.formatCellValue(val));
          if (col === this.settings.statusProperty && val != null) {
            const statusStr = typeof val === "object" ? JSON.stringify(val) : String(val);
            td.addClass(`arcadia-projects-status-${statusStr.toLowerCase().replace(/\s+/g, "-")}`);
          }
        }
      }
    }
  }
  toggleSort(column) {
    if (this.sortState && this.sortState.column === column) {
      if (this.sortState.direction === "asc") {
        this.sortState.direction = "desc";
      } else {
        this.sortState = null;
      }
    } else {
      this.sortState = { column, direction: "asc" };
    }
    this.renderTable();
  }
  formatColumnName(key) {
    if (key === "title")
      return "Title";
    return key.replace(/[-_]/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  }
  formatCellValue(val) {
    if (val == null)
      return "";
    if (Array.isArray(val))
      return val.join(", ");
    if (typeof val === "object")
      return JSON.stringify(val);
    return String(val);
  }
  destroy() {
    this.containerEl.empty();
  }
};

// src/kanban-view.ts
var import_obsidian4 = require("obsidian");
var KanbanView = class {
  constructor(app, containerEl, dataManager, settings) {
    this.draggedNote = null;
    this.app = app;
    this.containerEl = containerEl;
    this.dataManager = dataManager;
    this.settings = settings;
  }
  render() {
    var _a, _b;
    this.containerEl.empty();
    this.containerEl.addClass("arcadia-projects-kanban-container");
    const grouped = this.dataManager.getGroupedNotes(
      this.settings.statusProperty,
      this.settings.statusValues
    );
    if (this.dataManager.getNotes().length === 0) {
      const empty = this.containerEl.createDiv({ cls: "arcadia-projects-empty" });
      empty.setText("No notes found. Check your project folder setting.");
      return;
    }
    const board = this.containerEl.createDiv({ cls: "arcadia-projects-kanban-board" });
    const orderedKeys = [...this.settings.statusValues];
    for (const key of grouped.keys()) {
      if (key !== "__uncategorized__" && !orderedKeys.includes(key)) {
        orderedKeys.push(key);
      }
    }
    const uncategorized = (_a = grouped.get("__uncategorized__")) != null ? _a : [];
    if (uncategorized.length > 0) {
      orderedKeys.push("__uncategorized__");
    }
    for (const statusVal of orderedKeys) {
      const notes = (_b = grouped.get(statusVal)) != null ? _b : [];
      this.renderColumn(board, statusVal, notes);
    }
  }
  renderColumn(board, statusVal, notes) {
    const displayName = statusVal === "__uncategorized__" ? "Uncategorized" : statusVal;
    const column = board.createDiv({ cls: "arcadia-projects-kanban-column" });
    column.dataset.status = statusVal;
    const header = column.createDiv({ cls: "arcadia-projects-kanban-column-header" });
    header.createSpan({
      cls: "arcadia-projects-kanban-column-title",
      text: this.formatStatusName(displayName)
    });
    header.createSpan({
      cls: "arcadia-projects-kanban-column-count",
      text: `${notes.length}`
    });
    const cardsContainer = column.createDiv({ cls: "arcadia-projects-kanban-cards" });
    for (const note of notes) {
      this.renderCard(cardsContainer, note);
    }
    column.addEventListener("dragover", (e) => {
      e.preventDefault();
      column.addClass("arcadia-projects-kanban-column-dragover");
    });
    column.addEventListener("dragleave", (e) => {
      const related = e.relatedTarget;
      if (!related || !column.contains(related)) {
        column.removeClass("arcadia-projects-kanban-column-dragover");
      }
    });
    column.addEventListener("drop", (e) => {
      void (async () => {
        e.preventDefault();
        column.removeClass("arcadia-projects-kanban-column-dragover");
        if (this.draggedNote && statusVal !== "__uncategorized__") {
          await this.dataManager.updateNoteProperty(
            this.draggedNote.file,
            this.settings.statusProperty,
            statusVal
          );
          this.draggedNote = null;
        }
      })();
    });
    if (statusVal !== "__uncategorized__") {
      const addBtn = column.createDiv({ cls: "arcadia-projects-kanban-add-card" });
      addBtn.createSpan({ text: "+ Add card" });
      addBtn.addEventListener("click", () => {
        this.showCreateNoteModal(statusVal);
      });
    }
  }
  renderCard(container, note) {
    const card = container.createDiv({ cls: "arcadia-projects-kanban-card" });
    card.setAttribute("draggable", "true");
    const titleEl = card.createDiv({ cls: "arcadia-projects-kanban-card-title" });
    const link = titleEl.createEl("a", {
      text: note.title,
      cls: "arcadia-projects-note-link"
    });
    link.addEventListener("click", (e) => {
      e.preventDefault();
      void this.app.workspace.openLinkText(note.file.path, "", false);
    });
    const fieldsContainer = card.createDiv({ cls: "arcadia-projects-kanban-card-fields" });
    for (const field of this.settings.cardFields) {
      if (field === this.settings.statusProperty)
        continue;
      const rawFieldVal = note.properties[field];
      if (rawFieldVal == null || rawFieldVal === "")
        continue;
      const fieldEl = fieldsContainer.createDiv({ cls: "arcadia-projects-kanban-card-field" });
      fieldEl.createSpan({
        cls: "arcadia-projects-kanban-card-field-label",
        text: field + ": "
      });
      fieldEl.createSpan({
        cls: "arcadia-projects-kanban-card-field-value",
        text: this.formatValue(rawFieldVal)
      });
    }
    card.addEventListener("dragstart", (e) => {
      this.draggedNote = note;
      card.addClass("arcadia-projects-kanban-card-dragging");
      if (e.dataTransfer) {
        e.dataTransfer.effectAllowed = "move";
        e.dataTransfer.setData("text/plain", note.file.path);
      }
    });
    card.addEventListener("dragend", () => {
      card.removeClass("arcadia-projects-kanban-card-dragging");
      this.draggedNote = null;
      this.containerEl.querySelectorAll(".arcadia-projects-kanban-column-dragover").forEach((el) => el.removeClass("arcadia-projects-kanban-column-dragover"));
    });
  }
  formatStatusName(status) {
    return status.replace(/[-_]/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  }
  formatValue(val) {
    if (val == null)
      return "";
    if (Array.isArray(val))
      return val.join(", ");
    if (typeof val === "object")
      return JSON.stringify(val);
    return String(val);
  }
  showCreateNoteModal(statusVal) {
    const modal = new CreateNoteModal(this.app, this.dataManager, this.settings, statusVal);
    modal.open();
  }
  destroy() {
    this.containerEl.empty();
  }
};
var CreateNoteModal = class extends import_obsidian4.Modal {
  constructor(app, dataManager, settings, statusVal) {
    super(app);
    this.noteTitle = "";
    this.dataManager = dataManager;
    this.settings = settings;
    this.statusVal = statusVal;
  }
  onOpen() {
    const { contentEl } = this;
    new import_obsidian4.Setting(contentEl).setName("Create new note").setHeading();
    new import_obsidian4.Setting(contentEl).setName("Title").addText((text) => {
      text.setPlaceholder("Note title").onChange((value) => {
        this.noteTitle = value.trim();
      });
      setTimeout(() => text.inputEl.focus(), 50);
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          void this.createNote();
        }
      });
    });
    new import_obsidian4.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Create").setCta().onClick(() => {
        void this.createNote();
      });
    });
  }
  async createNote() {
    if (!this.noteTitle) {
      new import_obsidian4.Notice("Please enter a note title.");
      return;
    }
    try {
      const properties = {
        [this.settings.statusProperty]: this.statusVal
      };
      await this.dataManager.createNote(this.noteTitle, properties);
      new import_obsidian4.Notice(`Created "${this.noteTitle}"`);
      this.close();
    } catch (err) {
      new import_obsidian4.Notice(`Failed to create note: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/project-view.ts
var ProjectView = class extends import_obsidian5.ItemView {
  constructor(leaf, settings, dataManager) {
    super(leaf);
    this.tableView = null;
    this.kanbanView = null;
    this.contentContainerEl = null;
    this.settings = settings;
    this.dataManager = dataManager;
    this.currentMode = settings.defaultView;
    this.dataChangedHandler = () => this.renderCurrentView();
  }
  getViewType() {
    return VIEW_TYPE_ARCADIA_PROJECTS;
  }
  getDisplayText() {
    return "Arcadia projects";
  }
  getIcon() {
    return "layout-dashboard";
  }
  onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("arcadia-projects-root");
    const toolbar = container.createDiv({ cls: "arcadia-projects-toolbar" });
    const tabs = toolbar.createDiv({ cls: "arcadia-projects-tabs" });
    const tableTab = tabs.createDiv({ cls: "arcadia-projects-tab" });
    (0, import_obsidian5.setIcon)(tableTab.createSpan({ cls: "arcadia-projects-tab-icon" }), "table");
    tableTab.createSpan({ text: "Table" });
    tableTab.addEventListener("click", () => this.switchView("table"));
    const kanbanTab = tabs.createDiv({ cls: "arcadia-projects-tab" });
    (0, import_obsidian5.setIcon)(kanbanTab.createSpan({ cls: "arcadia-projects-tab-icon" }), "columns");
    kanbanTab.createSpan({ text: "Kanban" });
    kanbanTab.addEventListener("click", () => this.switchView("kanban"));
    const refreshBtn = toolbar.createDiv({ cls: "arcadia-projects-refresh-btn" });
    (0, import_obsidian5.setIcon)(refreshBtn, "refresh-cw");
    refreshBtn.setAttribute("aria-label", "Refresh");
    refreshBtn.addEventListener("click", () => {
      this.dataManager.refresh();
    });
    this.contentContainerEl = container.createDiv({ cls: "arcadia-projects-content" });
    this.dataManager.on("data-changed", this.dataChangedHandler);
    this.dataManager.refresh();
    this.updateTabStates();
  }
  onClose() {
    this.dataManager.off("data-changed", this.dataChangedHandler);
    this.destroyViews();
  }
  switchView(mode) {
    this.currentMode = mode;
    this.updateTabStates();
    this.renderCurrentView();
  }
  updateSettings(settings) {
    this.settings = settings;
    this.dataManager.updateSettings(settings);
    this.dataManager.refresh();
  }
  updateTabStates() {
    const tabs = this.containerEl.querySelectorAll(".arcadia-projects-tab");
    tabs.forEach((tab, index) => {
      if (index === 0 && this.currentMode === "table" || index === 1 && this.currentMode === "kanban") {
        tab.addClass("arcadia-projects-tab-active");
      } else {
        tab.removeClass("arcadia-projects-tab-active");
      }
    });
  }
  renderCurrentView() {
    if (!this.contentContainerEl)
      return;
    this.destroyViews();
    if (this.currentMode === "table") {
      this.tableView = new TableView(
        this.app,
        this.contentContainerEl,
        this.dataManager,
        this.settings
      );
      this.tableView.render();
    } else {
      this.kanbanView = new KanbanView(
        this.app,
        this.contentContainerEl,
        this.dataManager,
        this.settings
      );
      this.kanbanView.render();
    }
  }
  destroyViews() {
    if (this.tableView) {
      this.tableView.destroy();
      this.tableView = null;
    }
    if (this.kanbanView) {
      this.kanbanView.destroy();
      this.kanbanView = null;
    }
  }
};

// src/main.ts
var ArcadiaProjectsPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.dataManager = null;
  }
  async onload() {
    await this.loadSettings();
    this.dataManager = new ProjectDataManager(this.app, this.settings);
    this.registerView(VIEW_TYPE_ARCADIA_PROJECTS, (leaf) => {
      return new ProjectView(leaf, this.settings, this.dataManager);
    });
    this.addRibbonIcon("layout-dashboard", "Open Arcadia projects", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-project-view",
      name: "Open project view",
      callback: () => {
        void this.activateView();
      }
    });
    this.addCommand({
      id: "switch-to-table",
      name: "Switch to table view",
      callback: () => {
        this.switchView("table");
      }
    });
    this.addCommand({
      id: "switch-to-kanban",
      name: "Switch to kanban view",
      callback: () => {
        this.switchView("kanban");
      }
    });
    this.addSettingTab(new ArcadiaProjectsSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      var _a;
      (_a = this.dataManager) == null ? void 0 : _a.startListening();
    });
  }
  onunload() {
    var _a;
    (_a = this.dataManager) == null ? void 0 : _a.stopListening();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.dataManager) {
      this.dataManager.updateSettings(this.settings);
    }
    this.app.workspace.getLeavesOfType(VIEW_TYPE_ARCADIA_PROJECTS).forEach((leaf) => {
      if (leaf.view instanceof ProjectView) {
        leaf.view.updateSettings(this.settings);
      }
    });
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_ARCADIA_PROJECTS);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({
        type: VIEW_TYPE_ARCADIA_PROJECTS,
        active: true
      });
      this.app.workspace.revealLeaf(leaf);
    }
  }
  switchView(mode) {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_ARCADIA_PROJECTS);
    if (leaves.length > 0 && leaves[0].view instanceof ProjectView) {
      leaves[0].view.switchView(mode);
      this.app.workspace.revealLeaf(leaves[0]);
    } else {
      void this.activateView().then(() => {
        const newLeaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_ARCADIA_PROJECTS);
        if (newLeaves.length > 0 && newLeaves[0].view instanceof ProjectView) {
          newLeaves[0].view.switchView(mode);
        }
      });
    }
  }
};
